Created test for WC and API
ooni/probe-android pull request #370
Opened 2020-10-01 11:27 UTC by lorenzoPrimi

Part of https://github.com/ooni/backend/issues/450

2020-10-01 11:37 UTC, bassosimone requested changes

2020-10-01 11:37 UTC, bassosimone commented on app/src/androidTest/java/org/openobservatory/ooniprobe/test/WebConnectivityTest.java
> +        final CountDownLatch signal = new CountDownLatch(1);
This code is synchronous, so I think we don't need to use a countdown latch here.

2020-10-01 11:37 UTC, bassosimone commented on app/src/androidTest/java/org/openobservatory/ooniprobe/test/WebConnectivityTest.java
> +    private static final String MK_NAME = "WebConnectivity";
Maybe call this `EXPERIMENT_NAME`?

2020-10-01 11:40 UTC, bassosimone commented
What is missing:

- [ ] the API returns correct URL
- [ ] we run this test periodically using GHA

Regarding the latter, @lorenzoPrimi, I recommend checking how we do that in https://github.com/ooni/e2etesting/blob/master/.github/workflows/debian9.yml

2020-10-01 21:21 UTC, lorenzoPrimi commented on app/src/androidTest/java/org/openobservatory/ooniprobe/client/OONIAPIClientTest.java
>      private static final String NON_EXISTING_MEASUREMENT_URL = "https://api.ooni.io/api/v1/measurement/nonexistent-measurement-url";
In iOS we use `https://\t`

2020-10-02 17:18 UTC, bassosimone approved these changes
🐳

2020-10-04 18:42 UTC, merged