cleanup(engine): update to ooni/probe-cli >= 3.17.0-alpha
ooni/probe-android pull request #552
Opened 2023-01-08 14:53 UTC by bassosimone

We must use check-in now instead of using the URL list API, which has been removed from the codebase.

While there, remove code that was unused.

Part of https://github.com/ooni/probe/issues/2273.

2023-01-08 14:54 UTC, bassosimone commented on app/src/main/java/org/openobservatory/ooniprobe/test/TestAsyncTask.java
> +             */
@aanorbel what do you think is the best way to do this? (Ideally we'd like to factor some common code?)

2023-01-12 13:31 UTC, aanorbel requested changes

2023-01-12 13:31 UTC, aanorbel commented on engine/src/main/java/org/openobservatory/engine/OONICheckInConfig.java
> +            this.webConnectivity.addCategory(category);
Change from `add` to `addCategory` https://github.com/ooni/probe-cli/blob/master/pkg/oonimkall/session.go#L346 not available in engine . Causing build failure

2023-02-02 08:48 UTC, bassosimone commented on app/src/main/java/org/openobservatory/ooniprobe/common/ResubmitTask.java
> -            session.maybeUpdateResources(session.newContext());
The `maybeUpdateResources` API call has been a stub for quite some time. Removing it is harmless.

2023-02-02 08:48 UTC, bassosimone commented on app/src/main/java/org/openobservatory/ooniprobe/domain/GenerateAutoRunServiceSuite.java
> -
The `maybeUpdateResources` API call has been a stub for quite some time. Removing it is harmless.

2023-02-14 19:07 UTC, aanorbel approved these changes
LGTM

2023-03-07 20:44 UTC, merged