[New Designs] Update Chose websites view
ooni/probe-android pull request #630
Opened 2023-10-26 11:14 UTC by aanorbel

Fixes https://github.com/ooni/probe/issues/2592

## Proposed Changes

  - Updated `CustomWebsiteActivity` to use new theme.
  - Change List item builder to use  `RecyclerView`.

2023-12-01 13:00 UTC, bassosimone requested changes
Mostly 🐳. Maybe we need an issue for the TODO unless we want to address it as part of this pull request?

2023-12-05 16:58 UTC, bassosimone approved these changes
🐳 LGTM with minor suggestions

2023-12-05 16:58 UTC, bassosimone commented on app/src/main/java/org/openobservatory/ooniprobe/activity/customwebsites/CustomWebsiteActivity.kt
> +class CustomWebsiteActivity : AbstractActivity(), ConfirmDialogFragment.OnClickListener {
```suggestion
/** This activity allows a user to test a custom website. */
class CustomWebsiteActivity : AbstractActivity(), ConfirmDialogFragment.OnClickListener {
```

2023-12-05 16:58 UTC, bassosimone commented on app/src/main/java/org/openobservatory/ooniprobe/activity/customwebsites/CustomWebsiteActivity.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
```suggestion

    override fun onCreate(savedInstanceState: Bundle?) {
```

2023-12-05 17:05 UTC, aanorbel commented on app/src/main/java/org/openobservatory/ooniprobe/activity/OverviewActivity.java
> +import org.openobservatory.ooniprobe.activity.customwebsites.CustomWebsiteActivity;
Required at L106

2023-12-05 17:24 UTC, merged